# Generated by Django 2.2.5 on 2019-09-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('baseadvertising_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.BaseAdvertising')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('advertiser_management.baseadvertising',),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('baseadvertising_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertiser_management.BaseAdvertising')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('_advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.Advertiser')),
            ],
            bases=('advertiser_management.baseadvertising',),
        ),
    ]
